<?php

spl_autoload_register(function ($className) {
    static $preserve_key_word_list = [
        'abstract'     => 1,
        'and'          => 1,
        'array'        => 1,
        'as'           => 1,
        'break'        => 1,
        'callable'     => 1,
        'case'         => 1,
        'catch'        => 1,
        'class'        => 1,
        'clone'        => 1,
        'const'        => 1,
        'continue'     => 1,
        'declare'      => 1,
        'default'      => 1,
        'die'          => 1,
        'do'           => 1,
        'echo'         => 1,
        'else'         => 1,
        'elseif'       => 1,
        'empty'        => 1,
        'enddeclare'   => 1,
        'endfor'       => 1,
        'endforeach'   => 1,
        'endif'        => 1,
        'endswitch'    => 1,
        'endwhile'     => 1,
        'eval'         => 1,
        'exit'         => 1,
        'extends'      => 1,
        'final'        => 1,
        'finally'      => 1,
        'fn'           => 1,
        'for'          => 1,
        'foreach'      => 1,
        'function'     => 1,
        'global'       => 1,
        'goto'         => 1,
        'if'           => 1,
        'implements'   => 1,
        'include'      => 1,
        'include_once' => 1,
        'instanceof'   => 1,
        'insteadof'    => 1,
        'interface'    => 1,
        'isset'        => 1,
        'list'         => 1,
        'match'        => 1,
        'namespace'    => 1,
        'new'          => 1,
        'or'           => 1,
        'print'        => 1,
        'private'      => 1,
        'protected'    => 1,
        'public'       => 1,
        'readonly'     => 1,
        'require'      => 1,
        'require_once' => 1,
        'return'       => 1,
        'static'       => 1,
        'switch'       => 1,
        'throw'        => 1,
        'trait'        => 1,
        'try'          => 1,
        'unset'        => 1,
        'use'          => 1,
        'var'          => 1,
        'while'        => 1,
        'xor'          => 1,
        'yield'        => 1,
        'int'          => 1,
        'float'        => 1,
        'bool'         => 1,
        'string'       => 1,
        'true'         => 1,
        'false'        => 1,
        'null'         => 1,
        'void'         => 1,
        'iterable'     => 1,
        'object'       => 1,
        'mixed'        => 1,
        'never'        => 1,
    ];

    if (array_key_exists($className, $preserve_key_word_list)) {
        return;
    }

    $className = str_replace('\\', DIRECTORY_SEPARATOR, $className);
    $file = __DIR__ . DIRECTORY_SEPARATOR . $className . '.php';
    if (is_file($file)) {
        require $file;
    }
});